name: First Workflow
on: [push]

jobs:
  first_job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List and Read files
        run: |
          echo "My first github actions job"
          ls -ltra
          cat README.md

      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover, I'm a dragon!" >> dragon.txt
      
      # - name: List files
      #   run: ls -al
      
      # - name: Read file
      #   run: cat README.md